window.WaevePlayer=(()=>{
  const audio=new Audio(); audio.preload='metadata';
  let queue=[],index=-1,seeking=false;
  const settings=()=>WaeveStorage.get().settings||{};
  audio.volume=Number.isFinite(settings().volume)?settings().volume:.8;
  function current(){return queue[index]||null}
  function ensure(){if(document.querySelector('.waeve-player'))return;document.body.insertAdjacentHTML('beforeend',`<section class="waeve-player" aria-label="Waeve player"><div class="player-track"><div class="player-art" id="player-art">♫</div><div class="player-track-info"><strong id="player-title">Nothing playing</strong><span id="player-artist">Choose a song</span></div></div><div class="player-controls"><button id="player-shuffle" class="player-tool" aria-label="Shuffle">⇄</button><button id="player-prev" class="player-tool" aria-label="Previous">‹</button><button id="player-play" class="player-main" aria-label="Play">▶</button><button id="player-next" class="player-tool" aria-label="Next">›</button><button id="player-repeat" class="player-tool" aria-label="Repeat">↻</button></div><div class="player-progress"><span id="player-current">0:00</span><input id="player-progress" type="range" min="0" max="100" value="0" step="0.1" aria-label="Seek"><span id="player-duration">0:00</span></div><div class="player-volume"><button id="player-mute" aria-label="Mute">🔊</button><input id="player-volume" type="range" min="0" max="1" step="0.01" value="${audio.volume}" aria-label="Volume"><button id="player-queue" aria-label="Queue">☷</button></div></section>`);bind();syncButtons()}
  function bind(){const q=id=>document.getElementById(id);q('player-play').onclick=()=>audio.paused?audio.play():audio.pause();q('player-prev').onclick=previous;q('player-next').onclick=next;q('player-progress').oninput=e=>{seeking=true;if(audio.duration)audio.currentTime=audio.duration*e.target.value/100};q('player-progress').onchange=()=>seeking=false;q('player-volume').oninput=e=>{audio.volume=+e.target.value;WaeveStorage.patch({settings:{...settings(),volume:audio.volume}})};q('player-mute').onclick=()=>{audio.muted=!audio.muted;q('player-mute').textContent=audio.muted?'🔇':'🔊'};q('player-shuffle').onclick=()=>{WaeveStorage.patch({settings:{...settings(),shuffle:!settings().shuffle}});syncButtons()};q('player-repeat').onclick=()=>{const r=settings().repeat==='off'?'all':settings().repeat==='all'?'one':'off';WaeveStorage.patch({settings:{...settings(),repeat:r}});syncButtons()};q('player-queue').onclick=()=>renderQueue()}
  function syncButtons(){ensure();const s=settings();document.getElementById('player-shuffle').classList.toggle('active',!!s.shuffle);document.getElementById('player-repeat').classList.toggle('active',s.repeat!=='off');document.getElementById('player-repeat').textContent=s.repeat==='one'?'↻1':'↻'}
  function setQueue(list,start=0,autoplay=true){queue=[...list];index=Math.max(0,Math.min(start,queue.length-1));WaeveStorage.patch({queue:queue.map(t=>t.id),queueIndex:index});if(current())load(current(),autoplay)}
  function load(track,autoplay=false){ensure();const i=queue.findIndex(t=>t.id===track.id);if(i>=0)index=i;else{queue=[track];index=0}audio.src=track.src;audio.currentTime=0;update();if(autoplay)audio.play().catch(()=>WaeveUtils.toast('This track could not be played. Check the file.'))}
  function playTrack(track,list=WaeveMusic.all()){setQueue(list,Math.max(0,list.findIndex(t=>t.id===track.id)),true)}
  function next(){if(!queue.length)return;const s=settings();if(s.repeat==='one'){audio.currentTime=0;audio.play();return}if(s.shuffle&&queue.length>1){let n=index;while(n===index)n=Math.floor(Math.random()*queue.length);index=n}else index=(index+1)%queue.length;WaeveStorage.patch({queueIndex:index});load(queue[index],true)}
  function previous(){if(!queue.length)return;if(audio.currentTime>3){audio.currentTime=0;return}index=(index-1+queue.length)%queue.length;WaeveStorage.patch({queueIndex:index});load(queue[index],true)}
  function update(){const t=current();const title=document.getElementById('player-title'),artist=document.getElementById('player-artist'),art=document.getElementById('player-art');if(title){title.textContent=t?.title||'Nothing playing';artist.textContent=t?.artist||'Choose a song';art.textContent=t?.cover||'♫'}if(t)WaeveStorage.addRecent(t.id)}
  function renderQueue(){ensure();let box=document.getElementById('waeve-queue-panel');if(box){box.remove();return}box=document.createElement('aside');box.id='waeve-queue-panel';box.className='queue-panel';box.innerHTML=`<div class="queue-header"><strong>Queue</strong><button id="queue-close">×</button></div><div class="queue-list">${queue.map((t,i)=>`<button class="queue-item ${i===index?'current':''}" data-qidx="${i}"><span>${WaeveUtils.escape(t.title)}</span><small>${WaeveUtils.escape(t.artist)}</small></button>`).join('')||'<p class="queue-empty">Queue is empty.</p>'}</div>`;document.body.appendChild(box);document.getElementById('queue-close').onclick=()=>box.remove();box.querySelectorAll('[data-qidx]').forEach(b=>b.onclick=()=>{index=+b.dataset.qidx;load(queue[index],true);box.remove()})}
  audio.addEventListener('play',()=>{ensure();document.getElementById('player-play').textContent='❚❚'});audio.addEventListener('pause',()=>{ensure();document.getElementById('player-play').textContent='▶'});audio.addEventListener('ended',next);audio.addEventListener('loadedmetadata',()=>{const d=document.getElementById('player-duration');if(d)d.textContent=WaeveUtils.formatTime(audio.duration)});audio.addEventListener('timeupdate',()=>{const c=document.getElementById('player-current'),p=document.getElementById('player-progress');if(c)c.textContent=WaeveUtils.formatTime(audio.currentTime);if(p&&!seeking&&audio.duration)p.value=audio.currentTime/audio.duration*100});
  return{ensure,playTrack,setQueue,next,previous,current,audio};
})();
